language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-browserify' ]; then cd .. && eval "mv $currentfolder generator-browserify" && cd generator-browserify; fi

